### ISSUE TITLE
typedef struct HederaClient in hedera-client.h fails to compile

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-c#1]
hedera-client.h:37:16: note: forward declaration of 'struct HederaClient'
typedef struct HederaClient HederaClient;

seems the compiler doesn't like the duplicate ```HederaClient ``` names in the declaration.

**Comment by mehcode** [comment]
Those aren't duplicate names. An umbrella header needs to be added. And build instructions. I haven't put any work in making this SDK usable. It was only written as a bridge to push through Rust into Go.

**Comment by mehcode** [comment]
Closing as at least with clang and gcc it compiles fine. There was a couple other errors though which I fixed (don't remember now). The cgo parser Go uses is pretty lax apparently.
